#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2022-2024 Robin Vobruba <hoijui.quaero@gmail.com>
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# See the output of "$0 -h" for details.

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
#set -Eeuo pipefail
set -eu

script_path="$(readlink -f "$0")"
script_dir="$(dirname "$script_path")"
script_name="$(basename "$script_path")"

root_dir="$(cd "$script_dir/.."; pwd)"

print_help() {

	echo "$script_name - Generates the whole website."
	echo
	echo "Usage:"
	echo "  $script_name [OPTION...]"
	echo "Options:"
	echo "  -h, --help"
	echo "    Shows this help message and exit"
}

# read command-line args
i=1
while [ "$i" -lt "$#" ]
do
	arg="$(eval "echo \$$i")"

	case "$arg" in
		-h|--help)
			shift "$i"
			print_help
			exit 0
			;;
		*) # non-/unknown option
			i=$((i + 1))
			;;
	esac
done

cd "$root_dir/"

if [ -d .venv ]
then
	source .venv/bin/activate
fi
run/generate_summary
run/generate_diagrams

#mvd build
mvd clean
mvd generate
mvd make_html

menu_html="build/html/toc.html"
menu_js="build/html/toc.js"
echo "Removing non-menu items from the TOC ... (HACK)"

# echo awk -F"'" -e '
# BEGIN {
# 	inside = 0
# 	after = 0
# 	matchesStart = 0
# }
# 
# /this.innerHTML = '"'"'/ {
# 	if (inside || after) {
# 		print("ERROR: Found \"insideHTML\" more then once!") > /dev/stderr
# 	}
# 	inside = 1
# 	print($1 "'"'"'")
# 	insdideHtmlContent = $2
# 	matchesStart = 1
# }
# 
# {
# 	if (matchesStart) {
# 		matchesStart = 0
# 	} else {
# 		if (inside) {
# 			if (NF >= 2) {
# 				insdideHtmlContent = insdideHtmlContent $1
# 				print(insdideHtmlContent "'"'"'")
# 				insdideHtmlContent = ""
# 				inside = 0
# 				after = 1
# 			} else {
# 				insdideHtmlContent = insdideHtmlContent " " trim($0)
# 			}
# 		} else {
# 			print($0)
# 		}
# 	}
# }
# ' < "$menu_html"> "$menu_html.TMP"
# mv "$menu_html.TMP" "$menu_html"

grep -r "menu: false" **.md | sed -e 's/:.*//' | while read -r non_menu_file_md
do
	non_menu_file_html="${non_menu_file_md%md}html"
	# NOTE This fails on toc_html, because th TOC is not in a single line there, but we do not care about this file for now.
	sed -i -E -e 's|<li[^>]*><a href="'"$non_menu_file_html"'">[^<]*</a></li>||g' "$menu_html" "$menu_js"
done
